# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 173a8ce12f13765bd099ef04c933737a5ea418d28c1cdc1b75bc8c13d05495357a4506f7ec6dc09198954abe760faa441f7af7dc2c042b22e1b0d7dde2ebcfd8

test:
  secret_key_base: 5fd1197ff5bdb574231628a126ebceab91d56b9ce549935f77efa357282bbb0843afb6d67449b29af4a909dc7d803534a0c43996afa595d4a62f0c90d3df3186

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
